name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push for base image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: npakk/dotfiles:base
        file: ./base/Dockerfile
        platforms: linux/amd64, linux/arm64
        cache-to: type=local,dest=/tmp/docker-cache
        build-args: |
          GIT_NAME=${{ secrets.GIT_NAME }}
          GIT_EMAIL=${{ secrets.GIT_EMAIL }}

    - name: Build and push for dotfiles image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: npakk/dotfiles:dotfiles
        file: ./dotfiles/Dockerfile
        platforms: linux/amd64, linux/arm64
        cache-from: type=local,src=/tmp/docker-cache
        build-args: |
          GIT_NAME=${{ secrets.GIT_NAME }}
          GIT_EMAIL=${{ secrets.GIT_EMAIL }}

    - name: Build and push for ruby image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: npakk/dotfiles:ruby
        file: ./ruby/Dockerfile
        platforms: linux/amd64, linux/arm64
        cache-from: type=local,src=/tmp/docker-cache
        build-args: |
          GIT_NAME=${{ secrets.GIT_NAME }}
          GIT_EMAIL=${{ secrets.GIT_EMAIL }}
